<?php

    namespace App\Http\States\Application;

    use Spatie\ModelStates\State;
    use Spatie\ModelStates\StateConfig;

    abstract class ApplicationState extends State
    {
        abstract public function status();

        /**
         * @return void
         */
        public static function config(): StateConfig
        {
            return parent::config() // TODO: Change the autogenerated stub
            ->allowTransition(Pending::class, Success::class)
            ->allowTransition(Pending::class, Cancel::class);
        }
    }
