<?php

    namespace App\Http\States\Application;

    use Spatie\ModelStates\State;
    use Spatie\ModelStates\StateConfig;

    abstract class ApplicationState extends State
    {
//        abstract public function status():string;

        /**
         * @return void
         */
        public static function config(): StateConfig
        {
            return parent::config() // TODO: Change the autogenerated stub
            ->default(Pending::class)
            ->allowTransition(Pending::class, Success::class)
            ->allowTransition(Pending::class, Cancel::class)
            ->allowTransition(Success::class, Pending::class);
        }
    }
